version: '3'
services:
  myphp:
    build: ./dockerfiles/php
    container_name: myphp
    ports:
      - '9000:9000'
    volumes:
      - ./www:/www
      - ./dockerfiles/logs/php:/var/log/php
      - ./home:/home
      - ./root:/root
      - ./dockerfiles/php/etc:/usr/local/etc
    links:
      - 'mydb'
      - 'myredis'
    restart: always
    networks:
      - default
  mynginx:
    build: ./dockerfiles/nginx
    container_name: mynginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - myphp
    links:
      - myphp
    volumes:
      - ./dockerfiles/nginx/nginx:/etc/nginx
      # - ./dockerfiles/nginx/nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./dockerfiles/nginx/nginx/conf.d:/etc/nginx/conf.d
      - ./dockerfiles/logs/nginx:/var/log/nginx
      - ./www:/www
    restart: always
    networks:
      - default
    # environment:
    #   - TZ=Asia/Shanghai
    # command: nginx -g 'daemon off;'
  mydb:
    container_name: mydb
    build: ./dockerfiles/mysql
    ports:
      - '3306:3306'
    volumes:
      - ./dockerfiles/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      # MYSQL_DATABASE: xxxxx
      # MYSQL_USER: xxxxx
      # MYSQL_PASSWORD: xxxxx
  myredis:
    container_name: 'myredis'
    build: ./dockerfiles/redis
    ports:
      - '6379:6379'
    volumes:
      - ./dockerfiles/redis/data:/data
      # - ./dockerfiles/redis/conf:/etc/redis.conf
    restart: always
